name: diamondmoney
version: 2
main: me.anonymusdennis.diamondmoney.main
api-version: 1.17
load: POSTWORLD
depend: [Essentials]
commands:
  payout:
    description: collect your earnings
  money:
    description: shows your money / account balance
  balance:
    description: shows your money / account balance